- name: "deploy ssh-key to alpha.host"
  hosts: localhost
  connection: local
  vars_prompt:
    - name: passphrase
      prompt: Ask for passphrase ?
      private: yes
  vars:
    user: sysunicorns-operator
    group: sysunicorns-operator
  tasks:
    - name: Generate Key
      local_action: 
        module: community.crypto.openssh_keypair
        backend: cryptography
        comment: "{{user}}"
        path: "~/.ssh/{{user}}-key"
        private_key_format: "ssh"
        regenerate: full_idempotence
        passphrase: "{{passphrase}}"
        type: "ed25519"
        mode: 0600
        state: present
      delegate_facts: true

- name: "deploy ssh-key to alpha.host"
  hosts: alpha.host
  connection: ssh
  vars:
    user: sysunicorns-operator
    group: sysunicorns-operator
  vars_prompt:
    - name: ansible_user
      prompt: Ask user for connection ?
      private: yes
  tasks:
    - name: create sysunicorns-operator group
      ansible.builtin.group:
        name: "{{group}}"
        system: false
        state: present
      become: yes
    - name: create sysunicorns-operator user
      ansible.builtin.user:
        append: true
        create_home: true
        generate_ssh_key: false
        groups: "{{group}}, sudo"
        name: "{{user}}"
        state: present
        shell: /bin/bash
        system: no
      become: yes
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{user}}"
        state: present
        key: "{{ lookup('file', '~/.ssh/{{user}}-key.pub') }}"
      become: yes